development: 
  adapter: postgresql
  host: localhost 
  database: super_rad 
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>

production: 
  adapter: postgresql
  encoding: unicode 
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASS'] %>
